#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Framework;
using OpenAccess.Model;


namespace OpenAccess.Model	
{
	public partial class Category : NotificationObject
	{
		private int _categoryID;
		public virtual int CategoryID 
		{ 
		    get
		    {
		        return this._categoryID;
		    }
		    set
		    {
				if(this.CategoryID == value)
				{
					return;
				}
		
		        this._categoryID = value;
				this.RaisePropertyChanged("CategoryID");
		    }
		}
		
		private string _categoryName;
		public virtual string CategoryName 
		{ 
		    get
		    {
		        return this._categoryName;
		    }
		    set
		    {
				if(this.CategoryName == value)
				{
					return;
				}
		
		        this._categoryName = value;
				this.RaisePropertyChanged("CategoryName");
		    }
		}
		
		private string _description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
				if(this.Description == value)
				{
					return;
				}
		
		        this._description = value;
				this.RaisePropertyChanged("Description");
		    }
		}
		
		private byte[] _picture;
		public virtual byte[] Picture 
		{ 
		    get
		    {
		        return this._picture;
		    }
		    set
		    {
				if(this.Picture == value)
				{
					return;
				}
		
		        this._picture = value;
				this.RaisePropertyChanged("Picture");
		    }
		}
		
		private IList<Product> _products = new List<Product>();
		public virtual IList<Product> Products 
		{ 
		    get
		    {
		        return this._products;
		    }
		}
		
	}
}
