#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Framework;
using OpenAccess.Model;


namespace OpenAccess.Model	
{
	public partial class Order : NotificationObject
	{
		private int _orderID;
		public virtual int OrderID 
		{ 
		    get
		    {
		        return this._orderID;
		    }
		    set
		    {
				if(this.OrderID == value)
				{
					return;
				}
		
		        this._orderID = value;
				this.RaisePropertyChanged("OrderID");
		    }
		}
		
		private string _customerID;
		public virtual string CustomerID 
		{ 
		    get
		    {
		        return this._customerID;
		    }
		    set
		    {
				if(this.CustomerID == value)
				{
					return;
				}
		
		        this._customerID = value;
				this.RaisePropertyChanged("CustomerID");
		    }
		}
		
		private int? _employeeID;
		public virtual int? EmployeeID 
		{ 
		    get
		    {
		        return this._employeeID;
		    }
		    set
		    {
				if(this.EmployeeID == value)
				{
					return;
				}
		
		        this._employeeID = value;
				this.RaisePropertyChanged("EmployeeID");
		    }
		}
		
		private DateTime? _orderDate;
		public virtual DateTime? OrderDate 
		{ 
		    get
		    {
		        return this._orderDate;
		    }
		    set
		    {
				if(this.OrderDate == value)
				{
					return;
				}
		
		        this._orderDate = value;
				this.RaisePropertyChanged("OrderDate");
		    }
		}
		
		private DateTime? _requiredDate;
		public virtual DateTime? RequiredDate 
		{ 
		    get
		    {
		        return this._requiredDate;
		    }
		    set
		    {
				if(this.RequiredDate == value)
				{
					return;
				}
		
		        this._requiredDate = value;
				this.RaisePropertyChanged("RequiredDate");
		    }
		}
		
		private DateTime? _shippedDate;
		public virtual DateTime? ShippedDate 
		{ 
		    get
		    {
		        return this._shippedDate;
		    }
		    set
		    {
				if(this.ShippedDate == value)
				{
					return;
				}
		
		        this._shippedDate = value;
				this.RaisePropertyChanged("ShippedDate");
		    }
		}
		
		private int? _shipVia;
		public virtual int? ShipVia 
		{ 
		    get
		    {
		        return this._shipVia;
		    }
		    set
		    {
				if(this.ShipVia == value)
				{
					return;
				}
		
		        this._shipVia = value;
				this.RaisePropertyChanged("ShipVia");
		    }
		}
		
		private decimal? _freight;
		public virtual decimal? Freight 
		{ 
		    get
		    {
		        return this._freight;
		    }
		    set
		    {
				if(this.Freight == value)
				{
					return;
				}
		
		        this._freight = value;
				this.RaisePropertyChanged("Freight");
		    }
		}
		
		private string _shipName;
		public virtual string ShipName 
		{ 
		    get
		    {
		        return this._shipName;
		    }
		    set
		    {
				if(this.ShipName == value)
				{
					return;
				}
		
		        this._shipName = value;
				this.RaisePropertyChanged("ShipName");
		    }
		}
		
		private string _shipAddress;
		public virtual string ShipAddress 
		{ 
		    get
		    {
		        return this._shipAddress;
		    }
		    set
		    {
				if(this.ShipAddress == value)
				{
					return;
				}
		
		        this._shipAddress = value;
				this.RaisePropertyChanged("ShipAddress");
		    }
		}
		
		private string _shipCity;
		public virtual string ShipCity 
		{ 
		    get
		    {
		        return this._shipCity;
		    }
		    set
		    {
				if(this.ShipCity == value)
				{
					return;
				}
		
		        this._shipCity = value;
				this.RaisePropertyChanged("ShipCity");
		    }
		}
		
		private string _shipRegion;
		public virtual string ShipRegion 
		{ 
		    get
		    {
		        return this._shipRegion;
		    }
		    set
		    {
				if(this.ShipRegion == value)
				{
					return;
				}
		
		        this._shipRegion = value;
				this.RaisePropertyChanged("ShipRegion");
		    }
		}
		
		private string _shipPostalCode;
		public virtual string ShipPostalCode 
		{ 
		    get
		    {
		        return this._shipPostalCode;
		    }
		    set
		    {
				if(this.ShipPostalCode == value)
				{
					return;
				}
		
		        this._shipPostalCode = value;
				this.RaisePropertyChanged("ShipPostalCode");
		    }
		}
		
		private string _shipCountry;
		public virtual string ShipCountry 
		{ 
		    get
		    {
		        return this._shipCountry;
		    }
		    set
		    {
				if(this.ShipCountry == value)
				{
					return;
				}
		
		        this._shipCountry = value;
				this.RaisePropertyChanged("ShipCountry");
		    }
		}
		
		private Customer _customer;
		public virtual Customer Customer 
		{ 
		    get
		    {
		        return this._customer;
		    }
		    set
		    {
				if(this.Customer == value)
				{
					return;
				}
		
		        this._customer = value;
				this.RaisePropertyChanged("Customer");
		    }
		}
		
		private Employee _employee;
		public virtual Employee Employee 
		{ 
		    get
		    {
		        return this._employee;
		    }
		    set
		    {
				if(this.Employee == value)
				{
					return;
				}
		
		        this._employee = value;
				this.RaisePropertyChanged("Employee");
		    }
		}
		
		private Shipper _shipper;
		public virtual Shipper Shipper 
		{ 
		    get
		    {
		        return this._shipper;
		    }
		    set
		    {
				if(this.Shipper == value)
				{
					return;
				}
		
		        this._shipper = value;
				this.RaisePropertyChanged("Shipper");
		    }
		}
		
		private IList<OrderDetail> _orderDetails = new List<OrderDetail>();
		public virtual IList<OrderDetail> OrderDetails 
		{ 
		    get
		    {
		        return this._orderDetails;
		    }
		}
		
	}
}
