#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TelerikAcademy.Models;

namespace TelerikAcademy.Models	
{
	public partial class Group
	{
		private int _group_ID;
		public virtual int Group_ID
		{
			get
			{
				return this._group_ID;
			}
			set
			{
				this._group_ID = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private IList<User> _users = new List<User>();
		public virtual IList<User> Users
		{
			get
			{
				return this._users;
			}
		}
		
	}
}
#pragma warning restore 1591
