#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TelerikAcademy.Models;

namespace TelerikAcademy.Models	
{
	public partial class User
	{
		private int _user_ID;
		public virtual int User_ID
		{
			get
			{
				return this._user_ID;
			}
			set
			{
				this._user_ID = value;
			}
		}
		
		private string _username;
		public virtual string Username
		{
			get
			{
				return this._username;
			}
			set
			{
				this._username = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private string _fullName;
		public virtual string FullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				this._fullName = value;
			}
		}
		
		private DateTime? _lastLogin;
		public virtual DateTime? LastLogin
		{
			get
			{
				return this._lastLogin;
			}
			set
			{
				this._lastLogin = value;
			}
		}
		
		private int? _group_ID;
		public virtual int? Group_ID
		{
			get
			{
				return this._group_ID;
			}
			set
			{
				this._group_ID = value;
			}
		}
		
		private Group _group;
		public virtual Group Group
		{
			get
			{
				return this._group;
			}
			set
			{
				this._group = value;
			}
		}
		
	}
}
#pragma warning restore 1591
